version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc123
      MONGO_INITDB_DATABASE: ArgbControl

    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

volumes:
  mongo_data:
